import { Metadata } from "next";
import { getServices, getServicesCategoriesAPI } from "@/lib/api/actions/service";
import ServiceFilters from "@/components/serviceFilters";

export const metadata: Metadata = {
  title: "Services",
  description: "Generated by create next app",
};

export default async function Services() {
  const services = await getServices();
  const categories = await getServicesCategoriesAPI();

  return (
    <div className="p-10 lg:p-20">
      <p>BREADCRUMBS</p>
      <div className="w-full py-8 lg:w-[55%]">
        <h1 className="text-6xl font-semibold">
          Curated Sanctuaries for <i className="text-secondary-foreground">Modern Living</i>
        </h1>
        <p className="mt-5 text-xl">
          We combine clinical-grade sterilization protocols with a botanical, non-toxic ethos.
          Discover a level of clean that prioritizes your health and the environment.
        </p>
      </div>
      <ServiceFilters
        initialServices={services}
        initialCategories={categories}
      />
    </div>
  );
}
